# Generated by Django 5.2.6 on 2026-02-24 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('group', 'Group'), ('person', 'Person')], default='person', max_length=10, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('mini_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short description or tagline')),
                ('monthly_listeners', models.PositiveIntegerField(default=0, verbose_name='Number of listeners per month')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/artists/', verbose_name='Photo')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('history', models.TextField(blank=True, null=True, verbose_name='History')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('join_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Join date (Start career)')),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_artists', to=settings.AUTH_USER_MODEL, verbose_name='Managers')),
                ('genres', models.ManyToManyField(related_name='artists', to='orrin.genre', verbose_name='Genres')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/covers/', verbose_name='Cover image')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Audio file')),
                ('duration', models.PositiveIntegerField(blank=True, default=0, help_text='Тривалість треку у секундах', null=True, verbose_name='Тривалість')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='orrin.artist', verbose_name='Artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BandMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Join date')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='Leave date')),
                ('group', models.ForeignKey(limit_choices_to={'type': 'group'}, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='orrin.artist', verbose_name='Music group')),
                ('member', models.ForeignKey(limit_choices_to={'type': 'person'}, on_delete=django.db.models.deletion.CASCADE, related_name='band_memberships', to='orrin.artist', verbose_name='Artist')),
            ],
            options={
                'unique_together': {('member', 'group')},
            },
        ),
    ]
