# Generated by Django 5.2.6 on 2026-05-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('group', 'Group'), ('person', 'Person')], default='person', max_length=10, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('mini_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short description or tagline')),
                ('monthly_listeners', models.PositiveIntegerField(default=0, verbose_name='Number of listeners per month')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/artists/', verbose_name='Photo')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('history', models.TextField(blank=True, null=True, verbose_name='History')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('join_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Join date (Start career)')),
                ('socials', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BandMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Join date')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='Leave date')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/playlists/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'For Friends'), ('private', 'Private')], default='public', max_length=10, verbose_name='Visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order in playlist')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/covers/', verbose_name='Cover image')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Audio file')),
                ('duration', models.PositiveIntegerField(blank=True, default=0, help_text='Тривалість треку у секундах', null=True, verbose_name='Тривалість')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
