# Generated by Django 5.2.6 on 2026-05-22 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orrin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_artists', to=settings.AUTH_USER_MODEL, verbose_name='Managers'),
        ),
        migrations.AddField(
            model_name='bandmembership',
            name='group',
            field=models.ForeignKey(limit_choices_to={'type': 'group'}, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='orrin.artist', verbose_name='Music group'),
        ),
        migrations.AddField(
            model_name='bandmembership',
            name='member',
            field=models.ForeignKey(limit_choices_to={'type': 'person'}, on_delete=django.db.models.deletion.CASCADE, related_name='band_memberships', to='orrin.artist', verbose_name='Artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='orrin.genre', verbose_name='Genres'),
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='orrin.playlistmodel'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='orrin.artist', verbose_name='Artist'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='orrin.track'),
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='tracks',
            field=models.ManyToManyField(related_name='in_playlists', through='orrin.PlaylistTrack', to='orrin.track'),
        ),
        migrations.AlterUniqueTogether(
            name='bandmembership',
            unique_together={('member', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'track')},
        ),
    ]
