# Generated by Django 5.2.6 on 2026-05-07 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrin', '0002_alter_artist_genres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/playlists/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'For Friends'), ('private', 'Private')], default='public', max_length=10, verbose_name='Visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order in playlist')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='orrin.playlistmodel')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='orrin.track')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('playlist', 'track')},
            },
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='tracks',
            field=models.ManyToManyField(related_name='in_playlists', through='orrin.PlaylistTrack', to='orrin.track'),
        ),
    ]
