# Generated by Django 5.2.6 on 2025-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrin', '0003_track_audio_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(help_text='Тривалість треку у секундах'),
        ),
    ]
