# Generated by Django 5.2.6 on 2025-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
