# Generated by Django 5.2.6 on 2025-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrin', '0002_track_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
