# Generated by Django 5.2.6 on 2025-09-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orrin', '0004_alter_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=50, verbose_name='Виконавець'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/', verbose_name='Аудіо'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(upload_to='images/covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(help_text='Тривалість треку у секундах', verbose_name='Тривалість'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
    ]
